"""
validator.py — JSON Schema validation and OpenAPI document assembly.
"""
from __future__ import annotations

import json
import re
from typing import Any

import jsonschema

# ── Per-section endpoint schema ───────────────────────────────────────────────

ENDPOINT_SCHEMA: dict[str, Any] = {
    "type": "object",
    "required": ["endpoint", "http_method", "expected_parameters"],
    "properties": {
        "endpoint": {"type": "string"},
        "http_method": {
            "type": "string",
            "enum": ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"],
        },
        "expected_parameters": {
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name", "type", "required"],
                "properties": {
                    "name": {"type": "string"},
                    "type": {"type": "string"},
                    "required": {"type": "boolean"},
                    "description": {"type": "string"},
                },
            },
        },
        "inferred_rate_limit": {"type": "string"},
        "description": {"type": "string"},
        "response_schema": {"type": "object"},
    },
}


def validate_endpoint(data: dict) -> tuple[bool, str]:
    """Returns (is_valid, error_message)."""
    try:
        jsonschema.validate(instance=data, schema=ENDPOINT_SCHEMA)
        return True, ""
    except jsonschema.ValidationError as e:
        return False, e.message


def extract_json(raw: str) -> dict | None:
    """
    Extract the first JSON object from a raw model response string.
    Handles cases where the model wraps output in markdown code fences.
    """
    # Strip markdown fences
    raw = re.sub(r"```(?:json)?", "", raw).strip()

    # Try direct parse first
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass

    # Find first {...} block
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    return None


# ── OpenAPI 3.0 assembly ──────────────────────────────────────────────────────

def _param_to_openapi(param: dict) -> dict:
    type_map = {
        "string": "string",
        "str": "string",
        "integer": "integer",
        "int": "integer",
        "number": "number",
        "float": "number",
        "boolean": "boolean",
        "bool": "boolean",
        "array": "array",
        "object": "object",
    }
    schema_type = type_map.get(param.get("type", "string").lower(), "string")
    return {
        "name": param["name"],
        "in": "query",
        "required": param.get("required", False),
        "description": param.get("description", ""),
        "schema": {"type": schema_type},
    }


def build_openapi(title: str, endpoints: list[dict]) -> dict:
    """
    Merge a list of validated endpoint dicts into a single OpenAPI 3.0 document.
    """
    paths: dict[str, Any] = {}

    for ep in endpoints:
        path = ep.get("endpoint", "/unknown")
        method = ep.get("http_method", "GET").lower()
        params = ep.get("expected_parameters", [])
        description = ep.get("description", "")
        rate_limit = ep.get("inferred_rate_limit", "")

        operation: dict[str, Any] = {
            "summary": description or f"{method.upper()} {path}",
            "description": f"{description}\n\nRate limit: {rate_limit}".strip(),
            "parameters": [_param_to_openapi(p) for p in params],
            "responses": {
                "200": {"description": "Success"},
                "400": {"description": "Bad Request"},
                "429": {"description": "Rate limit exceeded"},
            },
        }

        if method in ("post", "put", "patch"):
            body_props = {
                p["name"]: {"type": p.get("type", "string")}
                for p in params
                if p.get("required", False)
            }
            operation["requestBody"] = {
                "required": True,
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": body_props,
                        }
                    }
                },
            }
            operation["parameters"] = []

        if path not in paths:
            paths[path] = {}
        paths[path][method] = operation

    return {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": "1.0.0",
            "description": f"Auto-generated by SpecValidator from '{title}'",
        },
        "paths": paths,
    }
